TrackerTemplate/TrackerTemplate/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TrackerTemplate.Models
{
    public class Vehicle
    {
        public int VehicleId { get; set; }

        public int GetVehicleId()
        {
            return VehicleId;
        }

        public void SetVehicleId(int value)
        {
            VehicleId = value;
        }

        [Required]
        public string Brand { get; set; }

        [Required]
        public string Model { get; set; }
        public string Color { get; set; }
        public string ProductionYear { get; set; }
        public string LicensePlate { get; set; }
        public string Owner { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime PurchaseDate { get; set; }
        [Required]
        public int Mileage { get; set; }
        public string Image { get; set; }
        [ForeignKey("dbo.AspNetUsers")]
        public string UserId { get; set; }
        public ICollection<ServiceBook> ServiceBooks { get; set; }
    }
}

TrackerTemplate/TrackerTemplate/Controllers/ServiceBookLogsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrackerTemplate.Models;
using TrackerTemplate.Models.AccountViewModels;

namespace TrackerTemplate.Controllers
{
    public class ServiceBookLogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<AppUser> userManager;

        public ServiceBookLogsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: ServiceBookLogs
        public async Task<IActionResult> Index()
        {
            var currentUserId = userManager.GetUserId(User);

            return View(await _context.ServiceBookLogs.ToListAsync());
        }

        // GET: ServiceBookLogs/Details/5
       
        public async Task<IActionResult> Details(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var serviceBookLog = await _context.ServiceBookLogs
                .FirstOrDefaultAsync(m => m.ServiceBookLogId == id);
            if (serviceBookLog == null)
            {
                return NotFound();
            }

            return View(serviceBookLog);
        }

        // GET: ServiceBookLogs/Create
      
        public IActionResult Create(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            return View();
        }

        // POST: ServiceBookLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceBookLogId,Date,Mileage,ServiceType,NextServiceDate,NextServiceMileage,VehicleWork,Details")] ServiceBookLog serviceBookLog)
        {
            var currentUserId = userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                _context.Add(serviceBookLog);
                await _context.SaveChangesAsync();

                int? id = int.Parse(RouteData.Values["id"].ToString());

                if (id != null)
                {
                    var serviceBooks = new ServiceBook[]
                    {
                    new ServiceBook{VehicleId=(int)id, ServiceBookLogId= serviceBookLog.ServiceBookLogId}
                    };

                    foreach (ServiceBook serviceBook in serviceBooks)
                    {
                        _context.ServiceBooks.Add(serviceBook);
                    }
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Details", "Vehicles", new { id });
            }
            return View(serviceBookLog);
        }

        // GET: ServiceBookLogs/Edit/5
      
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var serviceBookLog = await _context.ServiceBookLogs.FindAsync(id);
            if (serviceBookLog == null)
            {
                return NotFound();
            }
            return View(serviceBookLog);
        }

        // POST: ServiceBookLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceBookLogId,Date,Mileage,ServiceType,NextServiceDate,NextServiceMileage,VehicleWork,Details")] ServiceBookLog serviceBookLog)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id != serviceBookLog.ServiceBookLogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(serviceBookLog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceBookLogExists(serviceBookLog.ServiceBookLogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                var carId = _context.ServiceBooks.Where(x => x.ServiceBookId == id).Select(x => x.VehicleId).First();
                id = carId;

                return RedirectToAction("Details", "Vehicles", new { id });
            }
            return View(serviceBookLog);
        }

        // GET: ServiceBookLogs/Delete/5
     
        public async Task<IActionResult> Delete(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var serviceBookLog = await _context.ServiceBookLogs
                .FirstOrDefaultAsync(m => m.ServiceBookLogId == id);
            if (serviceBookLog == null)
            {
                return NotFound();
            }

            return View(serviceBookLog);
        }

        // POST: ServiceBookLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var currentUserId = userManager.GetUserId(User);

            var carId = _context.ServiceBooks.Where(x => x.ServiceBookId == id).Select(x => x.VehicleId).First();

            var serviceBookLog = await _context.ServiceBookLogs.FindAsync(id);
            _context.ServiceBookLogs.Remove(serviceBookLog);
            await _context.SaveChangesAsync();

            id = carId;

            return RedirectToAction("Details", "Vehicles", new { id });
        }

        private bool ServiceBookLogExists(int id)
        {
            return _context.ServiceBookLogs.Any(e => e.ServiceBookLogId == id);
        }
    }
}

TrackerTemplate/TrackerTemplate/Controllers/VehicleController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrackerTemplate.Models;
using TrackerTemplate.Models.AccountViewModels;

namespace TrackerTemplate.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> userManager;

        public VehiclesController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            var currentUserId = userManager.GetUserId(User);

            ViewData["BrandSortParm"] = String.IsNullOrEmpty(sortOrder) ? "brand_desc" : "";
            ViewData["ModelSortParm"] = sortOrder == "Model" ? "model_desc" : "Model";
            ViewData["CurrentFilter"] = searchString;

            var cars = from s in _context.Vehicles.Where(x => x.UserId == currentUserId)
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                cars = cars.Where(s => s.Brand.Contains(searchString)
                                       || s.Model.Contains(searchString));
            }

            cars = sortOrder switch
            {
                "brand_desc" => cars.OrderByDescending(s => s.Brand),
                "Model" => cars.OrderBy(s => s.Model),
                "model_desc" => cars.OrderByDescending(s => s.Model),
                _ => cars.OrderBy(s => s.Brand),
            };
            return View(await cars.AsNoTracking().ToListAsync());
        }

        // GET: Vehicles/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles
                .Include(c => c.ServiceBooks)
                .ThenInclude(s => s.ServiceBookLog)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.VehicleId == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Vehicles/Create

        public IActionResult Create()
        {
            var currentUserId = userManager.GetUserId(User);

            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Vehicle car, IFormFile image)
        {
            var currentUserId = userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                car.UserId = currentUserId;

                if (image != null && image.Length > 0)
                {
                    var fileName = string.Empty;

                    if (car.UserId != null)
                    {
                        fileName = $"{car.Brand}_{car.Model}_{car.UserId}.{image.FileName.Split('.').Last()}";
                    }
                    else
                    {
                        fileName = $"{car.Brand}_{car.Model}_null.{image.FileName.Split('.').Last()}";
                    }
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\carimages", fileName);
                    using (var fileSteam = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileSteam);
                    }
                    car.Image = fileName;
                }

                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Vehicles/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Vehicle car, IFormFile image)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id != car.GetVehicleId())
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null && image.Length > 0)
                    {
                        var fileName = string.Empty;

                        if (car.UserId != null)
                        {
                            fileName = $"{car.Brand}_{car.Model}_{car.UserId}.{image.FileName.Split('.').Last()}";
                        }
                        else
                        {
                            fileName = $"{car.Brand}_{car.Model}_null.{image.FileName.Split('.').Last()}";
                        }
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\carimages", fileName);
                        using (var fileSteam = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(fileSteam);
                        }
                        car.Image = fileName;
                    }
                    else
                    {
                        string currentUserIdString = string.Empty;

                        if (car.UserId == null)
                        {
                            currentUserIdString = "null";
                        }
                        else
                        {
                            currentUserIdString = car.UserId.ToString();
                        }

                        foreach (var carImage in _context.Vehicles.Select(x => x.Image))
                        {
                            if (carImage.Split('.').First().Split('_').Last() == currentUserIdString && carImage.Split('.').First().Split('_').First() == car.Brand
                                && carImage.Split('.').First().Split('_')[1] == car.Model)
                            {
                                car.Image = carImage;
                            }
                        }
                    }

                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(car.GetVehicleId()))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Vehicles/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.VehicleId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var currentUserId = userManager.GetUserId(User);

            string currentUserIdString = string.Empty;

            if (currentUserId == null)
            {
                currentUserIdString = "null";
            }
            else
            {
                currentUserIdString = currentUserId.ToString();
            }

            string rootFolder = @"wwwroot\\images\\carimages\\";

            foreach (var carImage in _context.Vehicles.Select(x => x.Image))
            {
                if (carImage.Split('.').First().Split('_').Last() == currentUserIdString)
                {
                    try
                    {
                        System.IO.File.Delete(Path.Combine(rootFolder, carImage));
                    }
                    catch (IOException)
                    {
                    }
                }

            }

            var car = await _context.Vehicles.FindAsync(id);
            _context.Vehicles.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicles.Any(e => e.VehicleId == id);
        }
    }
}

TrackerTemplate/TrackerTemplate/Views/Vehicles/Create.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Create";
}

<br />

<h2>Add a Vehicle</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label">Make</label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label">Model</label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label">Color</label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionYear" class="control-label">Year</label>
                <input asp-for="ProductionYear" class="form-control" />
                <span asp-validation-for="ProductionYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label">License Plage</label>
                <input asp-for="LicensePlate" class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label">Owner</label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseDate" class="control-label">Purchase Date</label>
                <input asp-for="PurchaseDate" class="form-control" />
                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage" class="control-label">Mileage</label>
                <input asp-for="Mileage" class="form-control" />
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Image</label>
                <br />
                <input asp-for="Image" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrackerTemplate/TrackerTemplate/Views/Vehicles/Delete.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Delete";
}

<br />
<h3>Are you sure you want to delete this record</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Make
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt>
           Model
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            Color
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            Year
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductionYear)
        </dd>
        <dt>
            License Plate
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LicensePlate)
        </dd>
        <dt>
            Owner
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt>
            Purchase Date
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
        <dt>
           Mileage
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="VehicleId" />
        <input type="submit" value="Изтрий" class="btn btn-danger" />
    </form>
</div>

TrackerTemplate/TrackerTemplate/Views/Vehicles/Details.cshtml
@model Vehicle
@{
    ViewData["Title"] = "Details";
}

<br />

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <div class="row">
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <div style="padding-left: 10px;">
                    <dd>
                        <img class="img-responsive rounded" style="max-width:500px; max-height:500px" src="@Url.Content("~/images/carimages/" + Model.Image)" alt="Vehicle Image">
                    </dd>
                </div>
            }
            <div class="col-md-6">
                <dt>
                    Make
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Brand)
                </dd>
                <dt>
                    Model
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Model)
                </dd>
                <dt>
                    Color
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Color)
                </dd>
                <dt>
                    year
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProductionYear)
                </dd>
                <dt>
                    License Plage
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LicensePlate)
                </dd>
                <dt>
                    Owner
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Owner)
                </dd>
                <dt>
                    Purchase Date
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.PurchaseDate)
                </dd>
                <dt>
                    Mileage
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Mileage)
                </dd>
            </div>
        </div>
        <br />
        <div>
            <a asp-action="Edit" asp-route-id="@Model.VehicleId" class="btn btn-primary"><i class="fas fa-edit"></i> Edit</a>
        </div>

        <hr />

        <div class="row">
            <div class="col-md-auto">
                <span><a asp-area="" asp-controller="ServiceBookLogs" asp-action="Create" asp-route-id="@Model.VehicleId" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Add an Entry of use"><i class="fas fa-wrench"></i>
                   Add to Entry Log </a></span>
            </div>
        </div>

        <br />

        <h4>Log Book</h4>

        <br />

        <dd class="col-sm-12">
            <table class="table">
                <tr>
                    <th>Date</th>
                    <th>Mileage</th>
                    <th>Service Type</th>
                    <th>Fuel Level</th>
                </tr>
                @foreach (var item in Model.ServiceBooks)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ServiceBookLog.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ServiceBookLog.CurrentMileage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ServiceBookLog.ServiceType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ServiceBookLog.CurrentFuelLevel)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="ServiceBookLogs" asp-route-id="@item.ServiceBookLog.ServiceBookLogId"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a> &nbsp;
                            <a asp-action="Details" asp-controller="ServiceBookLogs" asp-route-id="@item.ServiceBookLog.ServiceBookLogId"><button type="button" class="btn btn-info"><i class="fas fa-info-circle"></i></button></a> &nbsp;
                            <a asp-action="Delete" asp-controller="ServiceBookLogs" asp-route-id="@item.ServiceBookLog.ServiceBookLogId"><button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button></a>
                        </td>
                    </tr>
                }
            </table>
    </dl>
</div>

TrackerTemplate/TrackerTemplate/Views/Vehicles/Edit.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Edit";
}

<br />

<h2>Edit</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VehicleId" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label">Make</label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label">Model</label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label">Color</label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductionYear" class="control-label">Year</label>
                <input asp-for="ProductionYear" class="form-control" />
                <span asp-validation-for="ProductionYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label">License Plage</label>
                <input asp-for="LicensePlate" class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label">Owner</label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseDate" class="control-label">Purchase Date</label>
                <input asp-for="PurchaseDate" class="form-control" />
                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage" class="control-label">Mileage</label>
                <input asp-for="Mileage" class="form-control" />
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Image</label>
                <br />
                <input asp-for="Image" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrackerTemplate/TrackerTemplate/Views/Vehicles/Index.cshtml
@model IEnumerable<Vehicle>

@{
    ViewData["Title"] = "Index";
}

<br />

<h2>Vehicles</h2>

<hr />

<p>
    <a asp-action="Create"><button type="button" class="btn btn-primary"><i class="fas fa-plus"></i> Add A Vehicle</button></a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
           Find <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <a asp-action="Create"><button type="button" class="btn btn-primary"><i class="fas fa-search"></i> Search</button></a> 
            <a asp-action="Index" class="btn btn-primary"><i class="far fa-eye"></i> See Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["BrandSortParm"]">Make</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["ModelSortParm"]">Model</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VehicleId"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a> &nbsp;
                <a asp-action="Details" asp-route-id="@item.VehicleId"><button type="button" class="btn btn-info"><i class="fas fa-info-circle"></i> Service Booklet</button></a> &nbsp;
                <a asp-action="Delete" asp-route-id="@item.VehicleId"><button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button></a>
            </td>
        </tr>
}
    </tbody>
</table>