TrackerTemplate/TrackerTemplate/Controllers/DashboardController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrackerTemplate.Models;
using TrackerTemplate.Models.AccountViewModels;

namespace TrackerTemplate.Controllers
{

    public class DashboardController : Controller
    {
        private readonly UserManager<AppUser> userManager;

        public DashboardController(UserManager<AppUser> userManager)
        {
            this.userManager = userManager;
        }

        // Dashboard
        public IActionResult Index()
        {
            var currentUserId = userManager.GetUserId(User);

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrackerTemplate/TrackerTemplate/Controllers/FuelCalculatorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrackerTemplate.Models;
using TrackerTemplate.Models.AccountViewModels;

namespace TrackerTemplate.Controllers
{
    public class FuelCalculatorController : Controller
    {
        private readonly UserManager<AppUser> userManager;

        public FuelCalculatorController(UserManager<AppUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index(FuelCalculator model)
        {
            var currentUserId = userManager.GetUserId(User);

            return View();
        }
    }
}

TrackerTemplate/TrackerTemplate/Controllers/VehicleController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrackerTemplate.Models;
using TrackerTemplate.Models.AccountViewModels;

namespace TrackerTemplate.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> userManager;

        public VehiclesController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            var currentUserId = userManager.GetUserId(User);

            ViewData["BrandSortParm"] = String.IsNullOrEmpty(sortOrder) ? "brand_desc" : "";
            ViewData["ModelSortParm"] = sortOrder == "Model" ? "model_desc" : "Model";
            ViewData["CurrentFilter"] = searchString;

            var cars = from s in _context.Vehicles.Where(x => x.UserId == currentUserId)
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                cars = cars.Where(s => s.Brand.Contains(searchString)
                                       || s.Model.Contains(searchString));
            }

            cars = sortOrder switch
            {
                "brand_desc" => cars.OrderByDescending(s => s.Brand),
                "Model" => cars.OrderBy(s => s.Model),
                "model_desc" => cars.OrderByDescending(s => s.Model),
                _ => cars.OrderBy(s => s.Brand),
            };
            return View(await cars.AsNoTracking().ToListAsync());
        }

        // GET: Vehicles/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles
                .Include(c => c.ServiceBooks)
                .ThenInclude(s => s.ServiceBookLog)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.VehicleId == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Vehicles/Create

        public IActionResult Create()
        {
            var currentUserId = userManager.GetUserId(User);

            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Vehicle car, IFormFile image)
        {
            var currentUserId = userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                car.UserId = currentUserId;

                if (image != null && image.Length > 0)
                {
                    var fileName = string.Empty;

                    if (car.UserId != null)
                    {
                        fileName = $"{car.Brand}_{car.Model}_{car.UserId}.{image.FileName.Split('.').Last()}";
                    }
                    else
                    {
                        fileName = $"{car.Brand}_{car.Model}_null.{image.FileName.Split('.').Last()}";
                    }
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\carimages", fileName);
                    using (var fileSteam = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileSteam);
                    }
                    car.Image = fileName;
                }

                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Vehicles/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Vehicle car, IFormFile image)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id != car.GetVehicleId())
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null && image.Length > 0)
                    {
                        var fileName = string.Empty;

                        if (car.UserId != null)
                        {
                            fileName = $"{car.Brand}_{car.Model}_{car.UserId}.{image.FileName.Split('.').Last()}";
                        }
                        else
                        {
                            fileName = $"{car.Brand}_{car.Model}_null.{image.FileName.Split('.').Last()}";
                        }
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\carimages", fileName);
                        using (var fileSteam = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(fileSteam);
                        }
                        car.Image = fileName;
                    }
                    else
                    {
                        string currentUserIdString = string.Empty;

                        if (car.UserId == null)
                        {
                            currentUserIdString = "null";
                        }
                        else
                        {
                            currentUserIdString = car.UserId.ToString();
                        }

                        foreach (var carImage in _context.Vehicles.Select(x => x.Image))
                        {
                            if (carImage.Split('.').First().Split('_').Last() == currentUserIdString && carImage.Split('.').First().Split('_').First() == car.Brand
                                && carImage.Split('.').First().Split('_')[1] == car.Model)
                            {
                                car.Image = carImage;
                            }
                        }
                    }

                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(car.GetVehicleId()))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Vehicles/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            var currentUserId = userManager.GetUserId(User);

            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.VehicleId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var currentUserId = userManager.GetUserId(User);

            string currentUserIdString = string.Empty;

            if (currentUserId == null)
            {
                currentUserIdString = "null";
            }
            else
            {
                currentUserIdString = currentUserId.ToString();
            }

            string rootFolder = @"wwwroot\\images\\carimages\\";

            foreach (var carImage in _context.Vehicles.Select(x => x.Image))
            {
                if (carImage.Split('.').First().Split('_').Last() == currentUserIdString)
                {
                    try
                    {
                        System.IO.File.Delete(Path.Combine(rootFolder, carImage));
                    }
                    catch (IOException)
                    {
                    }
                }

            }

            var car = await _context.Vehicles.FindAsync(id);
            _context.Vehicles.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicles.Any(e => e.VehicleId == id);
        }
    }
}

TrackerTemplate/TrackerTemplate/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TrackerTemplate.Models

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

    <ul class="navbar-nav">
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
            </li>
        }

TrackerTemplate/TrackerTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tracker Template</title>
    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/css/simple-sidebar.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- for car comparison view -->
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Tracker</div>
            <div class="list-group list-group-flush">
                <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="list-group-item list-group-item-action bg-light"><i class="fas fa-tachometer-alt" style='font-size:20px'></i> DashboardBoard</a>
                <a asp-area="" asp-controller="FuelCalculator" asp-action="Index" class="list-group-item list-group-item-action bg-light"><i class='fas fa-calculator' style='font-size:20px'></i> Fuel Calculator </a>
                <a asp-area="" asp-controller="Vehicles" asp-action="Index" class="list-group-item list-group-item-action bg-light"><i class='fas fa-car' style='font-size:20px'></i> Vehicles</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-outline-secondary" id="menu-toggle" onclick="changeInnerHTML();"><i class="fas fa-arrow-left"></i></button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Login/Register
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <p class="dropdown-item"<a>@await Html.PartialAsync("_LoginPartial")</a></p>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Another Spot</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="container-fluid">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Tracker Template</p>
                </footer>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    <script type="text/javascript">
        function changeInnerHTML() {
            var leftButton = "<i class=\"fas fa-arrow-left\"></i>";
            var rightButton = "<i class=\"fas fa-arrow-right\"></i>";

            if (document.getElementById("menu-toggle").innerHTML == leftButton) {
                document.getElementById("menu-toggle").innerHTML = rightButton;
            }
            else {
                document.getElementById("menu-toggle").innerHTML = leftButton;
            }
        }
    </script>
</body>
</html>